### ISSUE TITLE
[BUG] can not see the third column of the visited websites

### ISSUE THREAD

**Issue by Daniel4078** [Wehrmachtserdbeere/MDRG-Analyzer#10] opened 2024-09-02 00:46 UTC
**Quick Summary**
I can not see the third column of the visited websites as I can not drag the slider at the bottom and can not resize the table window.

**To Reproduce**
1. Go to 'Websites' after loading file and select a save
2. See error

**What should happen**
Even with the visited websites being unchangeable, the slider should still be interact-able. Or allow us to change the shape of those table boxes.

**What actually happens**
I am not sure.

**Screenshots**
![image](https://github.com/user-attachments/assets/699b4d6f-ca2b-4b45-8f30-0bf7deb9c1b4)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome (I don't know if this info is relevant anyway as the game is an exe)
 - Version: 121.0.6167.185

**Device (please complete the following information, given they have any relevance to your issue):**
 - Device: Desktop
 - OS: Windows 10
 - Version 22H2

**Additional context**
I wonder if there is a way to change the default window size when I open the save analyzer, that way some of the texts will not be partially hidden behind input boxes.

**Comment by Wehrmachtserdbeere** [comment] 2024-09-02 00:48
Can you send over your save file so I can test it?

**Comment by Wehrmachtserdbeere** [comment] 2024-09-02 02:40
This error appears to be caused by your font. I will investigate a possible fix.

**Comment by Wehrmachtserdbeere** [comment] 2024-09-02 03:22
Fixed in [v1.1.5](https://www.github.com/Wehrmachtserdbeere/MDRG-Analyzer/tree/v1.1.5)

**Closed by Wehrmachtserdbeere** 2024-09-02 03:22 UTC
